"""Count occurrences of a pattern in text."""


def PatternCount(text: str, pattern: str) -> int:
    """Return the number of occurrences of pattern in text.

    Matches are case-sensitive and may overlap. Assume pattern is nonempty.
    Return 0 if pattern is longer than text or text is empty.

    Example:
        PatternCount("AAAA", "AA") returns 3.
    """

    count = 0
    for i in range(0, text.__len__()):
        if pattern == text[i:i+pattern.__len__()]:
            count += 1
    return count


# ros q
# Currently when you load the module, it prints the result for this!
print(PatternCount("TTGCTTCGTGTGCTTCGGGGGCGCAAGGTGCTTCGTATGCTTCGGTCTGCTTCGAGGTGCTTCGCTGCTTCGTACCTTGCTTCGTGCTTCGGTGGCTGTGCTTCGACATATGCTTCGTAGATTGCTTCGCTGCTTCGCTGCTTCGACAGTGCTTCGGTGCTTCGTGCTTCGTATGCCCTGCTTCGGTATTGTTATGCTTCGCACGGGTGCTTCGATGCTTCGCTTGCTTCGTGCTTCGTGCTTCGGGGGGGGTTGCTTCGGTCTGCTTCGTGCTTCGTCGATCTGCTTCGGCTGGGTGCTTCGGAGGGATTAGCCGTTACCGTGCTTCGGGCAATTGCTTCGGACTCTGGATGCTTCGGGTGCTTCGGCGATATACTTGTTGCTTCGAACGAAAGGCTGCTTCGGTGCTTCGTTGCTTCGATGCTTCGAGACCTGCTTCGGCCGTGCTTCGTGCTTCGCATTAAGCCGTGCTTCGCGTGCTTCGTGCTTCGGCTGCTTCGTGCTTCGTGCTTCGCTGCTTCGTGCTTCGTATTATATGCTTCGGGTTGCTTCGTACTGCTTCGGTGCTTCGTTGCTTCGAACGATTGCTTCGATGCTTCGGTGCTTCGAATGCGCGTTGCTGTGCTTCGTGCTTCGTGCTTCGTGCTTCGTGCTTCGTTGCTTCGTGCTTCGGTTGCTTCGGTGCTTCGGGCACCTGCTTCGTGTGCTGAGTGCTTCGCTTCGTGTGCTTCGTGTGCTTCGGAAGTCTACCCTGCTTCGGCCTTCATGCTTCGCTGCTTCGATGCTTCGTAATTGCTTCGGCTGCTTCGTTGCTTCGGTGCTTCGGCAGACTGCTTCGCTATGCTTCGAGGAGGTGCTTCGTGCTTCGTGCTTCGCCCTGCTTCGCAAATGCTTCGATGCTTCGTGCTTCGGTGCTTCGTGCTTCGTTGCTTCGTTGCTTCGGTGCTTCGTGCTTCGTGCTTCGTG", "AA"))